<?php
    class Seeder{
        private static $seeder = null;
        private $db;

        private function Seeder(){
            $this->db = new DataBase;
            $this->insert(); 
        }

        public  static  function create(){ 
            if (self::$seeder == null){ 
                self::$seeder = new Seeder;
            }
            return self::$seeder;
        }

        # Insercion de datos en Category sumbtema y tema
        public function insert(){  
            $this->db->query("INSERT INTO `author_type`(`author_type_id`, `author_type_identifier`)
                                VALUES ('1','Principal'),('2','Ilustrador'),('3','Co-autor')");

            $this->db->query("INSERT INTO `topic`(`topic_cdu`, `topic_name`)
                                VALUES ('0','GENERALIDADES'),
                                ('1',  'FILOSOFIA'),
                                ('2',  'RELIGION'),
                                ('3',  'CIENCIAS SOCIALES'),
                                ('37', 'EDUCACION'),
                                ('5',  'CIENCIAS PURAS'),
                                ('6',  'CIENCIAS APLICADAS'),
                                ('7',  'ARTE Y DEPORTE'),
                                ('8',  'LINGUISTICA Y LITERATURA'),
                                ('9',  'GEOGRAFIA, BIOGRAFIAS E HISTORIA')
                            ");
                            
            $this->db->query("INSERT INTO `subtopic`(`subtopic_id`, `subtopic_name`, `topic_cdu`)
                                VALUES ('0','Generalidades','0'),
                                    ('1','Filosofia','1'),
                                    ('5','PSICOLOGIA','1'),
                                    ('6','LOGICA','1'),
                                    ('2','Religion','2'),
                                    ('3','Ciencias sociales','3'),
                                    ('16','Sociologia','3'),
                                    ('32','Politica','3'),
                                    ('33','Economia Y trabajo','3'),
                                    ('34','Derecho','3'),
                                    ('35','Administracion Publica','3'), 
                                    ('355','Fuerzas Armadas','3'),
                                    ('36','Trabajo Social','3'),
                                    ('39','ETNOLOGIA-FOLKLORE-USOS Y COSTUMBRES-VIDA SOCIAL','3'),
                                    ('37','Educacion.Enseñanza ','37'),
                                    ('51','MATEMATICAS','5'),
                                    ('52','ASTRONOMIA-GEODESIA','5'),
                                    ('53','FISICA','5'),
                                    ('54',' QUIMICA','5'),
                                    ('55','Geologia y Ciencias Afines','5'),
                                    ('57','Biologia','5'),
                                    ('61','Medicina','6'),
                                    ('619','Veterinaria','6'),
                                    ('62','INGENIERIA','6'),
                                    ('63','AGRICULTURA, GANADERIA Y PESCA','6'),
                                    ('65','COMUNICACIONES','6'),
                                    ('659','GESTION DE EMPRESAS, DE PRODUCTOS Y SERVICIOS','6'),
                                    ('66','INDUSTRIA Y TECNOLOGIA','6'),
                                    ('70','ARTE','7'),
                                    ('79','DEPORTES','7'),
                                    ('80','LINGÜISTICA. FILOLOGIA','8'),
                                    ('82','LITERATURA','8'),
                                    ('90','GEOGRAFIA','9'),
                                    ('92','BIOGRAFIAS','9'),
                                    ('93','HISTORIA','9')
                            ");
            $this->db->query("INSERT INTO category (category_name,category_cod, subtopic_id)
                                VALUES ('GENERALIDADES EN CIENCIA','001','0'), 
                                    ('CIENCIA Y CONOCIMEINTO GENERAL EN LA ARGENTINA ','001[82]','0'),
                                    ('METODOLOGIA DE LA INVESTIGACION,ASPECTOS TEORICOS DE LA INVESTIGACION,ANALISIS DE DATOS','001.8','0'),
                                    ('COMUNICACION,CIBERNETICA  ','007','0'),
                                    ('CULTURA,PROGRESO ','008','0'),
                                    ('BIBLIOTECOLOGIA  ','020','0'),
                                    ('MUSEOLOGIA ','069','0'),
                                    ('PERIODISMO, LIBERTAD DE PRENSA ','070','0'),
                                    ('POLIGRAFIAS INDIVIDUALES Y COLECTIVAS CULTURA PROGRESO ','080','0'),
                                    ('MISCELENEA ','088','0'),
                                    ('POLIGRAFIAS INDIVIDUALES Y COLECTIVAS CULTURA PROGRESO ','080','0'),
                                    ('FILOSOFIA SU ESENCIA Y SU METODO ','1','1'),
                                    ('HISTORIA DE LA FILOSOFIA','1[091]','1'),
                                    ('FILOSOFIA EN LA ARGENTINA','1[82]','1'),
                                    ('FILOSOFIA ANTIGUA','1-1','1'),
                                    ('FILOSOFIA MEDIVAL','1-2','1'),
                                    ('FILOSOFIA MODERNA','1-3','1'),
                                    ('FILOSOFIA CONTEMPORANEA','1-4','1'),
                                    ('METAFISICA','11','1'),
                                    ('COSMOLOGIA','113/119','1'),
                                    ('CIENCIAS OCULTAS','113','1'),
                                    ('SISTEMAS FILOSOFICOSESTUDIOS SOBRE OBRAS DE FILOSOFOS','141','1'),
                                    ('CIENCIAS OCULTAS','113','1'),
                                    ('PSICOLOGIA (Generalidades)','159.9','5'),
                                    ('HISTORIA DE LA PSICOLOGIA','159.9[091]','5'),
                                    ('INVESTIGACIONES EXPERIMENTALES,TEST DE INVESTIGACION','159.9.07','5'),
                                    ('TEORIA Y TECNICAS DE GRUPO','159.90','5'),
                                    ('SALUD MENTAL,PSICOLOGIA PREVENTIVA,PSICOLOGIA FORENSE','159.91','5'),
                                    ('PSICOLOGIA COMPARADA Y DIFERENCIAL','159.92','5'),
                                    ('PSICOLOGIA Y EPISTEMOLOGIA GENETICA ,PIAGET (todas las obras de Piaget)','159.922','5'),
                                    ('PSICOLOGIA DE LA INFANCIA PSICOLOGIA EVOLUTIVA','159.922.7','5'),
                                    ('PSICOLOGIA DE LA ADOLESCENCIA','159.922.8','5'),
                                    ('TIPOLOGIA,PERSONALIDAD,TEMPERAMENTO,CARACTEROLOGIA,MOTIVACION','159.923','5'),
                                    ('PSICOLOGIA GENERAL,PERCEPCION,ATENCION,MEMORIA,SENSACION,PENSAMIENTO','159.93','5'),
                                    ('VIDA AFECTIVA,CARACTERISTICAS DE LA SENSIBILIDAD,ESTADOS,EMOCIONALES,AUTOAYUDA,AUTOPERFECCIONAMIENTO','159.94','5'),
                                    ('PSICOANALISIS','159.964.2','5'),
                                    ('OTRAS ESCUELAS DE PSICOTERAPIA','159.964.26','5'),
                                    ('PSICOPATOLOGIA','159.97','5'),
                                    ('PSICOLOGIA SOCIAL(la obra de Pichón Riviére)','159.98','5'),
                                    ('Psicologia institucional','159.99','5'),
                                    ('TEORIA Y TECNICAS DE GRUPO','159.90','5'),
                                    ('Logica','16','6'),
                                    ('TEORIA  DEL CONOCIMIENTO','165','6'),
                                    ('ETICA-CUESTIONES DEL CONOCIMIENTO','170','6'),
                                    ('RELIGION-TEOLOGIA-ATEISMO','21','2'),
                                    ('LA BIBLIA-ANTIGUO TESTAMENTO-NUEVO TESTAMENTO','22','2'),
                                    ('TEOLOGIA DOGMATICA-ARTE Y SIMBOLOS CRISTIANOS-ASCETICA. ESPIRITUALIDAD-IGLESIA CRISTIANA-EVANGELIZACION-ORDENES. CONGREGACIONES','23/27','2'),
                                    ('COMUNIDADES RELIGIOSAS VARIAS-SECTAS','28','2'),
                                    ('MITOLOGIA-CIENCIA E HISTORIA COMPARADA DE LAS RELIGIONES','29','2'),
                                    ('RELIGIONES DE LOS PUEBLOS GERMANICOS Y BALTOESLAVOS','293','2'),
                                    ('RELIGIONES DE LA INDIA-HINDUISMO-RELIGIONES PERSAS','294/295','2'),
                                    ('RELIGION JUDIA -EL JUDAISMO','296','2'),
                                    ('EL CORAN -EL ISLAMISMO','297','2'),
                                    ('RELIGIONES DE LOS PUEBLOS AFRICANOS','299.6','3'),
                                    ('RELIGIONES DE LOS PUEBLOS DE AMERICA','299.7/8','2'),
                                    ('TEORIAS DE LAS CIENCIAS SOCIALES-GENERALIDADES DE LAS CIENCIAS SOCIALES','30','3'),
                                    ('CUESTION SOCIAL EN GENERAL-POLITICAS SOCIALES-POBREZA, MINORIDAD, FAMILIA','304','3'),
                                    ('CUESTION SOCIAL EN LA ARGENTINA-POLITICAS SOCIALES-POBREZA-PROBLEMAS DE MINORIDAD Y FAMILIA','304[82]','3'),
                                    ('ESTADISTICA COMO CIENCIA-TEORIA DE LA ESTADISTICA-INVESTIGACION ESTADISTICA','311','3'),
                                    ('DEMOGRAFIA','314','3'),
                                    ('MIGRACION-INMIGRACION Y EMIGRACION-TRASLADOS DE POBLACION','314.7','3'),
                                    ('Sociologia','316','16'),
                                    ('SOCIOLOGIA EN LA ARGENTINA','316[82]','16'),
                                    ('ESTRUCTURA SOCIAL-SOCIEDAD COMO SISTEMA SOCIAL-TIPOS SOCIO-ECONOMICOS DE SOCIEDADES GLOBALES','316.3','16'),
                                    ('SOCIOLOGIA URBANA Y RURAL','316.33','16'),
                                    ('ESTRATIFICACION SOCIAL-CLASES SOCIALES-GRUPOS Y CAPAS SOCIALES-MOVILIDAD SOCIAL-MARGINALIDAD-RACISMO-DISCRIMINACION','316.34','16'),
                                    ('PROCESOS SOCIALES','316.4','16'),
                                    ('Sociologia de la cultura','316.7','16'),
                                    ('politica','32','32'),
                                    ('POLITICA ARGENTINA','32[82]','32'),
                                    ('FORMAS DE LA ORGANIZACION POLITICA-LOS ESTADOS COMO PODERES POLITICOS-SOBERANIA-MONARQUIA-DICTADURA-DEMOCRACIA','321','32'),
                                    ('MOVIMIENTOS NACIONALES-MINORIAS NACIONALES-IRREDENTISMO-MOVIMIENTOS CONTRA CIERTAS RAZAS Y NACIONALISMOS-REGIONALISMOS','323.1','32'),
                                    ('REVOLUCION-GOLPE DE ESTADO-INSURRECCION-GUERRA CIVIL-PERSECUCION POLITICA','323.2','32'),
                                    ('COLONIZACION-OCUPACION DE TERRITORIOS-TIPOS DE COLONIAS (penales, militares, de explotación económica)','325','32'),
                                    ('RELACIONES POLITICAS INTERNACIONALES-POLITICA INTERNACIONAL-POLITICA EXTERIOR-IMPERIALISMO-INTERNACIONALISMO','327','32'),
                                    ('PARTIDOS Y MOVIMIENTOS POLITICOS','329','32'),
                                    ('PARTIDOS POLITICOS EN LA ARGENTINA','329[82]','32'),
                                    ('ECONOMIA -ECONOMIA POLITICA','330','33'),
                                    ('HISTORIA DE LA ECONOMIA','330[091]','33'),
                                    ('ECONOMIA DE LATINOAMERICA MERCOSUR','330[7/8]','33'),
                                    ('ECONOMIA -ECONOMIA POLITICA','330[82]','33'),
                                    ('HISTORIA DE LAS TEORIAS ECONOMICAS-TEORIAS ECONOMICAS ANTERIORES AL SIGLO XX','330.8','33'),
                                    ('TRABAJO-HISTORIA DEL TRABAJO-ECONOMIA DEL TRABAJO','331','33'),
                                    ('HISTORIA DEL TRABAJO EN ARGENTINA','331[82]','33'),
                                    ('CONDICIONES Y MEDIO AMBIENTE DE TRABAJO-SEGURIDAD EN EL TRABAJO','331.4','33'),
                                    ('MERCADO DEL TRABAJO-EMPLEO','331.5','33'),
                                    ('SINDICATOS-CONFLICTOS LABORALES. NEGOCIACION COLECTIVA-ORGANIZACION INTERNACIONAL DEL TRABAJO','331.91','33'),
                                    ('ECONOMIA REGIONAL-POLITICA ECONOMICA REGIONAL','332','33'),
                                    ('FORMAS DE ORGANIZACION Y COOPERACION EN LA ECONOMIA','334','33'),
                                    ('FINANZAS-HACIENDA PUBLICA-PRESUPUESTOS DEL ESTADO','336','33'),
                                    ('SITUACION ECONOMICA<POLITICA ECONOMICA-INDUSTRIA COMO SECTOR ECONOMICO<ECONOMIA DEL TRANSITO Y COMUNICACIONES','338','33'),
                                    ('SITUACION ECONOMICA EN LA ARGENTINA-POLITICA ECONOMICA EN LA ARGENTINA','338[82]','33'),
                                    ('MERCADOS-COMERCIO INTERIOR-COMERCIO EXTERIOR','339','33'),
                                    ('DERECHO ARGENTINO','34[82]','34'),
                                    ('HISTORIA DEL DERECHO','34[091]','34'),
                                    ('LEYES<DECRETOS-EDICTOS--PROYECTOS DE LEY-REGLAMENTOS','34[094]','34'),
                                    ('DERECHO-CIENCIAS AUXILIARES DEL DERECHO-DERECHO COMPARADO-TIPOS Y FORMAS DEL DERECHO','340','34'),
                                    ('DERECHO INTERNACIONAL-ORGANISMOS ESPECIALIZADOS DE GOBIERNO MUNDIAL','341','34'),
                                    ('DERECHO DE GUERRA-ESTADO DE GUERRA O BELIGERANCIA-DECLARACION DE GUERRA','341.3','34'),
                                    ('DERECHO POLITICO','342','34'),
                                    ('CONSTITUCIONES<REFORMA CONSTITUCIONAL-ASAMBLEAS NACIONALES','342.4','34'),
                                    ('DERECHO PARLAMENTARIO-PODERES DEL ESTADO','342.5','34'),
                                    ('DERECHOS FUNDAMENTALES<DERECHOS HUMANOS-DERECHOS Y DEBERES DE LOS CIUDADANOS','342.7','34'),
                                    ('DERECHO PENAL-DELITOS PENALES<PREVENCION DEL DELITO','343','34'),
                                    ('DERECHO PENAL MILITAR-DERECHO PENAL MARITIMO-DERECHO PENAL AERONAUTICO','344','34'),
                                    ('DERECHO CIVIL EN GENERAL-ORIGEN DE LOS DERECHOS','347','34'),
                                    ('DERECHOS REALESDERECHOS DE LA PROPIEDAD-DERECHO PRIVADO','347.2','34'),
                                    ('OBLIGACIONES-CONTRATOS','347.4','34'),
                                    ('DERECHO DE FAMILIA-DERECHO MATRIMONIAL-DERECHO DE SUCESIONES','347.6','34'),
                                    ('DERECHO AEREO-DERECHO ESPACIAL-DERECHO DE LA RADIODIFUSION','347.8','34'),
                                    ('DERECHO PROCESAL-PROCEDIMIENTO CIVIL','347.9','34'),
                                    ('DERECHO ECLESIASTICO-DERECHO CANONICO-DERECHO EN LAS DIFERENTES RELIGIONES','348','34'),
                                    ('RAMAS ESPECIALES DEL DERECHO-DERECHO DEL TRABAJO-DERECHO SOCIAL-DERECHO AGRARIO-DERECHO URBANISTICO-DERECHO AMBIENTAL','349','34'),
                                    ('ORGANIZACION ADMINISTRATIVA -ADMINISTRACION PUBLICA DE LA ECONOMIA','345','35'),
                                    ('ARTE Y CIENCIAS MILITARES EN GENERAL-HISTORIA DE LAS DIFERENTES ARMAS-DEFENSA NACIONAL-ARMAS DE TIERRA, AIRE Y MAR-SOCIOLOGIA DE LA GUERRA-POLICIA MILITAR-FUERZAS ARMADAS EN GENERAL','355/359','355'),
                                    ('TRABAJO SOCIAL-PROBLEMAS GENERALES QUE INFLUYEN EN EL BIENESTAR-PERSONAS QUE TRABAJAN EN LA ASISTENCIA SOCIAL','36','36'),
                                    ('ORGANIZACION ADMINISTRATIVA -ADMINISTRACION PUBLICA DE LA ECONOMIA','366','36'),
                                    ('TURISMO','379.85','36'),
                                    ('SEGUROS-CLASES DE EMPRESAS DE SEGUROS','368','36'),
                                    ('CONSUMISMO --PAPEL DEL CONSUMIDOR EN LA ECONOMIA Y EN LA SOCIEDAD-RIESGOS DEL CONSUMIDO','366','36'),
                                    ('ETNOGRAFIA -ANTROPOLOGIA CULTURAL Y SOCIAL-ANTROPOLOGIA FISICA Y/O BIOLOGICA','39','39'),
                                    ('VESTIMENTA-MASCARAS-TATUAJES','391','39'),
                                    ('USOS Y COSTUMBRES EN LA VIDA PRIVADA ','392','39' ),
                                    ('MUERTE. FUNERALES (ritos)', '393','39'), 
                                    ('FIESTAS NACIONALES-FESTEJOS POPULARES-CEREMONIAS OFICIALES-CEREMONIAL-DIPLOMACIA','394','39'), 
                                    ('FEMINISMO-MUJER (emancipación, igualdad, derecho, trabajo, política, etc.)','396','39'), 
                                    ('FOLKLORE PROPIAMENTE DICHO (tradiciones, sabiduría popular)CREENCIAS Y TRADICIONES-JUEGOS POPULARES-CANCIONERO POPULAR. DICHOS POPULARES-MARIONETAS. TITERES','398','39') ,
                                    ('FOLKLORE ARGENTINO', '398[82]','39'),
                                    ('CIENCIA DE LA EDUCACION', '37','37'),
                                    ('PEDAGOGOS ','37:929','37'), 
                                    ('HISTORIA DE LA EDUCACION (propiamente dicha)', '37[091]','37'), 
                                    ('LEGISLACION EDUCATIVA-RESPONSABILIDAD CIVIL DOCENTE (en general)-CONVALIDACION DE TITULOS','37[094]','37'),
                                    ('EDUCACION EN TODOS LOS PAISES QUE NO CONFORMAN AMERICA LATINA ','37[4/9]','37'), 
                                    ('EDUCACION EN AMERICA LATINA (solo temáticas muy generales.', '37[7/8]','37'), 
                                    ('HISTORIA DE LA EDUCACION EN LA ARGENTINA ','37[82][091]','37'),
                                    ('LEGISLACION EDUCATIVA ARGENTINA-ESTATUTO DEL DOCENTE-LEY FEDERAL DE EDUCACION','37[82][094] ','37'),
                                    ('FILOSOFIA DE LA EDUCACION','37.011','37'),#hasta aca
                                    ('INVESTIGACION EDUCATIVA<METODOS DE INVESTIGACION EDUCATIVA-INVESTIGACION-ACCION-EDUCACION COMPARADA','37.012 ','37'),
                                    ('TEORIA GENERAL DE LA EDUCACION -PEDAGOGIA-CONCEPTOS GENERALES DE EDUCACION','37.013 ','37'),
                                    ('POLITICA EDUCATIVA-ESTADO Y EDUCACION-DERECHO A LA EDUCACIOn-EDUCACION Y VIDA PUBLICA-CRISIS DE LA EDUCACION-CALIDAD DE LA EDUCACION-SISTEMAS EDUCATIVOs','37.014 ','37'),
                                    ('ESCUELA PUBLICA-EDUCACION PUBLICA-DESERCION ESCOLAR','37.014.2','37'),
                                    ('ANALFABETISMO-ALFABETIZACION DE ADULTOS','37.014.22','37'),
                                    ('REFORMAS EDUCATIVAS ','37.014.3','37'),
                                    ('PLANEAMIENTO EDUCATIVO- NACIONAL-REGIONAL ','37.014.5','37'),
                                    ('POLITICA DE LA EDUCACION SEGUN PUNTOS DE VISTA-ECONOMICOS-FINANCIACION DE LA EDUCACION','37.014.54','37'),
                                    ('PSICOLOGIA DE LA EDUCACION','37.015','37'),
                                    ('ANTROPOLOGIA DE LA EDUCACION-SOCIOLOGIA PEDAGOGICA-SOCIOMETRIA PEDAGOGICA-SOCIOLOGIA DE LA EDUCACION','37.015.4 ','37'),
                                    ('APRENDIZAJE-FRACASO ESCOLAR-TRASTORNOS DEL APRENDIZAJE','37.015.5','37'),
                                    ('EDUCACION A DISTANCIA-ESTUDIOS NOCTURNOS-EDUCACION PERMANENTE',' 37.018','37'),
                                    ('EDUCACION EN FAMILIA','37. 018.1','37'),
                                    ('CUESTIONES GENERALES DE DIDACTICA Y METODOLOGIA-METODO DE PROYECTOS','37.02','37'),
                                    ('METODOS Y TECNICAS DE ESTUDIO','37.025','37'),
                                    ('EDUCACION PARA LA SALUD-HIGIENE ESCOLAR','37.03 ','37'),
                                    ('EDUCACION SEXUAL','37.031','37'),
                                    ('EDUCACION MORAL,EDUCACION EN VALORES','37.034 ','37'),
                                    ('TEMAS TRANSVERSALES-EDUCACION PARA LA PAZ-EDUCACION DEL CONSUMIDOR-EDUCACION PARA LA IGUALDAD-EDUCACION VIAL','37.034.1','37'),
                                    ('EDUCACION POLITICA','37.035','37'),
                                    ('ORIENTACION ESCOLAR-COEDUCACION. EDUCACION INTEGRADA Y SEGREGADA-SEXISMO EN EDUCACION -FORMACION AUTODIDACTA','37.04 ','37'),
                                    ('ORIENTACION VOCACIONALCONSEJO PEDAGOGICO-ORIENTACION PROFESIONAL-ORIENTACION POR PADRES Y DOCENTES','37.048','37'),
                                    ('RELACIONES ENTRE PADRES, DOCENTES, COMUNIDAD ALUMNOS-RELACIONES HUMANAS-AMBIENTE EDUCACIONAL','37.06','37'), 
                                    ('ORGANIZACION DE LA EDUCACION Y LA ENSEÑANZA','371','37'),
                                    ('PERSONAL DOCENTE-PERSONAL AUXILIAR<ROL DOCENTE','371.12','37'),
                                    ('FORMACION DE LOS PROFESORES Y EDUCADORES-PERFECCIONAMIENTO DOCENTE-PERFECCIONAMIENTO DOCENTE EN SERVICIO3','371.13','37'),
                                    ('ORGANIZACION DE LAS INSTITUCIONES EDUCATIVAS Y DE LA ENSEÑANZA (a nivel escuela) GESTION INSTITUCIONAL',' 371.2 ','37'),
                                    ('PLANES DE ESTUDIOS<PROGRAMAS ESCOLARES.CURRICULO<CONTENIDOS BASICOS COMUNES','371.214','37'),
                                    ('ACTOS ESCOLARES.CEREMONIAS ESCOLARES','371.239','37'),
                                    ('APRECIACION Y SUPERVISION DE LOS PROFESORES A LOSALUMNOS (notas, informes, tests) EXAMENES. CALIFICACIONES TITULOS. DIPLOMAS EVALUACION','371.27','37'),
                                    ('METODOS DE ENSEÑANZA PROCEDIMIENTOS DE ENSEÑANZA','371.3','37'),
                                    ('TALLERES.AULA-TALLER.DINAMICA DE GRUPO.TRABAJO EN EQUIPOCLUBES ESCOLARES','371.311','37'),
                                    ('ENSEÑANZA PROGRAMADA (o instrucción programada)','371.315','37'),
                                    ('TRABAJO MANUAL','371.38','37'),
                                    ('METODO ACTIVO','371.382','37'),
                                    ('PERIODISMO ESCOLAR','371.385 ','37'),
                                    ('TRABAJOS PRACTICOS DE LABORATORIO -EXPERIENCIAS CIENTIFICAS','371.388','37'),
                                    ('DISCIPLINA ESCOLAR-REGLAMENTOS, REGLAS DE CONDUCTA, COMPORTAMIENTO-SANCIONES','371.5','37'),
                                    ('EMPLAZAMIENTO DE ESTABLECIMIENTOS EDUCATIVOS<EDIFICACIONES. ARQUITECTURA ESCOLAR-MOBILIARIO','371.6','37'),
                                    ('MATERIAL AUDIOVISUAL','371.68','37'),
                                    ('VIDA DE LOS ESTUDIANTES (costumbres)-INTERCAMBIO ESTUDIANTI','371.8','37'),
                                    ('EDUCACION PREESCOLAR-JARDIN DE INFANTES-GUARDERIAS-NIVEL INICIAL','372.3','37'),
                                    ('ENSEÑANZA GENERAL BASICA (EGB 1 Y 2)-ENSEÑANZA PRIMARIA','372.4','37'),
                                    ('LA LECTURA.LECTOESCRITURA INICIAL<COMPRENSION LECTORA<EXPRESION ORAL. VOCABULARIO','372.41','37'),
                                    ('ESCRITURAENSEÑANZA DE LA REDACCIO','372.45','37'),
                                    ('LA ENSEÑANZA DE LA LENGUA (para Primaria y EGB, a nivelgeneral)','372.46','37'),
                                    ('ELEMENTOS DE GRAMATICA Y ORTOGRAFIA','372.462','37'),
                                    ('EDUCACION BILINGÜEDI-DACTICA DE LOS IDIOMAS','372.80','37'),
                                    ('DIDACTICA DE LA FILOSOFIA','372.81 ','37'),
                                    ('DIDACTICA DE LA PSICOLOGIA','372.815','37'),
                                    ('DIDACTICA DE LA RELIGION','372.82 ','37'),
                                    ('DIDACTICA DE LAS CIENCIAS SOCIALES (Primaria y EGB)','372.83','37'),
                                    ('DIDACTICA DE LA FORMACION ETICA Y CIUDADANA-DIDACTICA DE LA EDUCACION CIVICA','372.835','37'),
                                    ('DIDACTICA DE LAS CIENCIAS NATURALES-DIDACTICA DE LA EDUCACION AMBIENTAl','372.85','37'),
                                    ('DIDACTICA DE LAS MATEMATICAS (Primaria /Media)','372.851','37'),
                                    ('DIDACTICA DE LA FISICA','372.853','37'),
                                    ('DIDACTICA DE LA QUIMICA','372.85' ,'37'),
                                    ('DIDACTICA DE LA TECNOLOGIA','372.86 ','37'),
                                    ('DIDACTICA DE LA INFORMATICA.USO DE SOFTWARE y HARDWARE EDUCATIVO','372. 868','37'),
                                    ('DIDACTICA DE LAS ARTES PLASTICAS-ARTE INFANTIL-ENSEÑANZA DEL DIBUJO. PINTURA. CERAMICA','372.87','37'),
                                    ('DIDACTICA DE LA MUSICA','372.878','37'),
                                    ('DIDACTICA DE LA EDUCACION FISICA','372.879','37'),
                                    ('TEATRO ESCOLAR-TITERES','372.879.2 ','37'),
                                    ('ENSEÑANZA DE LENGUA Y LITERATURA','372.88','37'),
                                    ('DIDACTICA DE LA GEOGRAFIA ','372.891','37'),
                                    ('DIDACTICA DE LA HISTORIA','372.893','37'),
                                    ('ENSEÑANZA SECUNDARIA','373.5 ','37'),#hasta aca
                                    ('ENSEÑANZA TECNICA (Escuelas Técnicas)','373.62 ','37'),
                                    ('EDUCACION RURAL,ESCUELAS UNITARIAS','373.68 ','37'),
                                    ('EDUCACION DE ADULTOS-EDUCACION Y TERCERA EDAD','374.7 ','37'),
                                    ('EDUCACION ESPECIAL (discapacitados físicos / mentales)','376','37'),
                                    ('EDUCACION DE PERSONAS EN SITUACION SOCIAL ESPECIAL-PRIVILEGIADOS SOCIALESHUERFANOS (abandonados).MARGINACION','376.6 ','37'),
                                    ('FORMACION PROFESIONAL-ESCUELAS PROFESIONALES-FORMACION Y ENSEÑANZA DE PROFESIONES NO','377 ','37'),
                                    ('EDUCACION Y EMPLEO','377.3','37'),
                                    ('ENSEÑANZA SUPERIOR/ TERCIARIA','378','37'),
                                    ('EDUCACION EN TIEMPO LIBRE ','379.8 ','37'),
                                    ('MATEMATICAS. GENERALIDADES< GEOMETRIA ALGEBRAICA-GRUPOS DE LIE','51','51'),
                                    ('ARITMETICA-TEORIA DE NUMEROS','511 ','51'),
                                    ('ALGEBRA-TEORIA DE LOS GRUPOS','512 ','51'),
                                    ('GEOMETRIA (trigonometría, geometría, euclideana, analítica, métrica).POLIGONOMETRIA-GEOMETRIA DIFERENCIAL-GEOMETRIA ANALITICA-GEOMETRIA DESCRIPTIVA','514','51'),
                                    ('ANALISIS MATEMATICOCALCULO DIFERENCIAL-TEORIA DE FUNCIONES-ANALISIS COMBINATORIO-DETERMINANTES FUNCIONALE-SCALCULO INTEGRAL','517 ','51'),
                                    ('TEORIA GENERAL DEL ANALISIS COMBINATORIO-TEORIA DE LOS GRUPOS-PROBABILIDADES Y ESTADISTICA MATEMATICA-MATEMATICAS COMPUTACIONALES-CIBERNETICA MATEMATICA-INVESTIGACION OPERATIVA ','519.1','51'),
                                    ('ASTRONOMIA-INSTRUMENTOS ASTRONOMICOS-TECNICAS DE OBSERVACION-MECANICA CELESTE-ASTRONOMIA ESFERICA-SISTEMA SOLAR-ESTRELLAS Y SISTEMAS ESTELARES--EL UNIVERSO','52','52'),
                                    ('GEODESIA-MEDICION A DISTANCIA (para obtener a distancia información sobre-propiedades físicas y químicas de la tierra)-CARTOGRAFIA (trazado de mapas)-AGRIMENSURA (medición catastral)-INSTRUMENTOS DE MEDICION','528','52'),
                                    ('FISICA ECANICA RACIONAL.FUERZA-EQUILIBRIO-FUERZA DE ATRACCION-HIDRAULICA-ACUSTICA. VIBRACIONES<CAMPOS ESPECIALES Y COMPLEJOS DE LA MECANICA-BIOMECANICA','53 ','53'),
                                    ('OPTICA-TEORIA DE LA LUZ-POLARIZACION-COLORES Y SUS PROPIEDADES','535','53'),
                                    ('TERMODINAMICA-CALOR','536 ','53'),
                                    ('ELECTRICIDAD-MAGNETISMO-ELECTROMAGNETISMO','537','51'),
                                    ('CONSTITUCION FISICA DE LA MATERIA-FISICA NUCLEAR, ATOMICA Y MOLECULAR','539 ','53'),
                                    ('QUIMICA ,QUIMICA ANALITICA-QUIMICA FISICA','54','54'),
                                    ('QUIMICA INORGANICA','546 ','54'),
                                    ('qUIMICA ORGANICA','547 ','54'),
                                    ('CRISTALOGRAFIA.ESTUDIO ESPECIAL SOBRE LOS MINERALES',' 548/549 ','54'),
                                    ('GEOLOGIA.GEOFISICA-GEOQUIMICA<GEOBIOLOGIA-VULCANOLOGIA-SISMOLOGIA-COSMOGONIA-GLACIOLOGIA-GEOMORFOLOGIA (forma física de la tierra, continentes, islas, etc.)-ESPELEOLOGIA ',' 55 ','55'),
                                    ('OCEANOGRAFIA','551.46 ','55'),
                                    ('METEOROLOGIA -CLIMATOLOGIA',' 551.5','55'),
                                    ('PETROLOGIA (estudio de las rocas, meteoritos)-PETROGRAFIA','552','55'),
                                    ('HIDROSFERA (agua en general)-CICLOS DEL AGUA-CORRIENTES SUBTERRANEAS-SISTEMAS FLUVIALES ','556 ','55'),
                                    ('PALEONTOLOGIA (clases y zonas de fósiles)-ANIMALES PREHISTORICOS-PALEOBOTANICA-PALEOZOOLOGIA',' 56 ','55'),
                                    ('BIOLOGIA (teoría y principios generales)-MICROORGANISMOS (las plantas y los animales como forma de vida)-ORIGEN DE LA VIDA','573 ','57'),
                                    ('ECOLOGIA Y MEDIO AMBIENTE<POBLACIONES BIOLOGICAS Y SU HABITAT-ECOSISTEMAS Y CADENAS ALIMENTARIASDISTRIBUCION GEOGRAFICA DE LOS SERES VIVOS','574','57'),
                                    ('BOTANICA','581','57'),
                                    ('ZOOLOGIA','59','57'),
                                    ('ETOLOGIA (modo de vida de los animales, psicología de los animales)','591.5','57'),
                                    ('HISTORIA DE LA MEDICINA',' 61[091]','61'),
                                    ('ANATOMIA HUMANA','611','61'),
                                    ('EMBRIOLOGIA,GENETICA' ,'611.013 ','61'),
                                    ('BIOLOGIA CELULAR Y MOLECULAR',' 611.018 ','61'),
                                    ('MICROBIOLOGIA PARASITOLOGIA','611.02','61'),
                                    ('BIOQUIMICA',' 611.020','61'),
                                    ('FISIOLOGIA HUMANA',' 612','61'),
                                    ('INMUNOLOGIA',' 612.017 ','61'),
                                    ('HEMATOLOGIA (composición química y propiedades físicas de lasangre)','612.1 ','61'),
                                    ('NUTRICION (alimentos en general, su asimilación, dietas)','612.39','61'),
                                    ('FONOAUDIOLOGIA',' 612.78','61'),
                                    ('HIGIENE PERSONAL (en la alimentación, la ropa, las costumbres,higiene sexual)<DROGADEPENDENCIA ',' 613','61'),
                                    ('GERONTOLOGIA','613.98','61'),
                                    ('SALUD PUBLICA',' 614','61'),
                                    ('FARMACOLOGIA',' 615','61'),
                                    ('FISIOTERAPIATERAPIAS VARIAS-MEDICINAS ALTERNATIVAS-REMEDIOS CASEROS','615.8','61'),
                                    ('TOXICOLOGIA GENERAL-INTOXICACIONES',' 615.9','61'),
                                    ('MEDICINA INTERNASEMIOLOGIA-<CARDIOLOGIA-GASTROENTEROLOGIA (enfermedades de los órganos digestivos)-ENDOCRINOLOGIA-DERMATOLOGIA<UROLOGIA.HEMATOLOGIA<OTORRINOLARINGOLOGIA-NEUMOLOGIA.PATOLOGIA','616','61'),
                                    ('PEDIATRIA','616-053.2','61'),
                                    ('ODONTOLOGIA','616.314','61'),
                                    ('NEUROLOGIA (afecciones de los nervios).SISTEMA NERVIOSO CENTRAL Y PERIFERICO','616.8','61'),
                                    ('PSIQUIATRIA','616.89','61'),
                                    ('ENFERMEDADES INFECCIOSAS.ENFERMEDADES TRANSMISIBLES.SIDA','616.9','61'),
                                    ('ORTOPEDIA','617 ','61'),
                                    ('OFTALMOLOGIA','617.7 ','61'),
                                    ('GINECOLOGIA Y OBSTETRICIA','618','61'),
                                    ('MEDICINA VETERINARIA-ANATOMIA ANIMAL-HISTOLOGIA ANIMAL-ENFERMEDADES DE LOS ANIMALES DOMESTIC','619','619'),
                                    ('ENSAYO DE MATERIALES-ECONOMIA DE LA ENERGIA.CONOCIMIENTO DE LOS PRODUCTOS','620','62'),
                                    ('ENERGIA NUCLEAR Y ATOMICA EN GENERAL','621.039 ','62'),
                                    ('ELECTROTECNICA.ELECTRONICA-TELECOMUNICACIONES<TECNOLOGIA MECANICA EN GENERAL<MOTORES','621.3/9','62'),
                                    ('INGENIERIA DE MINAS','622','62'),
                                    ('INDUSTRIA E INGENIERIA MILITAR Y NAVAL','623','62'),
                                    ('NGENIERIA CIVIL (construcción de viviendas, edificios)ESTRUCTURAS HIDRAULICAS-INGENIERIA DE LA ILUMINACION','624/628','62'),
                                    ('INGENIERIA DEL TRANSPORTE','629','62'),
                                    ('TECNICA DE VUELO ESPACIAL-ASTRONAUTICA-NAVES AEREAS','629.78','62'),
                                    ('AGRICULTURA',' 631','63'),
                                    ('CULTIVOS ESPECIFICOS','633','63'),
                                    ('HORTICULTURA','635 ','63'),
                                    ('ZOOTECNIA EN GENERAL.APICULTURA .GANADO EQUINO.GANADO BOVINO Y GRANDES RUMIANTES.GANADO OVINO',' 636','63'),
                                    ('PRODUCTOS DE LOS ANIMALES DOMESTICOS, DE CAZA Y PESCA','637','63'),
                                    ('CAZA PESCA PISCICULTURA','639','63'),
                                    ('ECONOMIA DOMESTICA (pública y privada)-RESTAURANTES (casas de comida, salones de té, bares, cafeterías)-ALIMENTOS Y SU PREPARACION','64  ','63'),
                                    ('TELECOMUNICACION (organización y gestión)-TELEGRAFIA (transmisión de noticias)-TELEFONIA (técnicamente)-TELEVISION(idem)-RADIO','654','65'), 
                                    ('TRANSPORTES DE TODO TIPO-CORREOS','656','65'), 
                                    ('CONTABILIDAD-AUDITORIA-SISTEMAS CONTABLES','657','659'), 
                                    ('ADMINISTRACION DE EMPRESAS-TECNICA COMERCIAL-CLASES DE EMPRESAS-FINANZAS-ORGANIZACION DE MERCADOS (Marketing)-VENTAS-CALIDAD TOTAL-PERSONAL','658','659'), 
                                    ('PUBLICIDAD Y PROPAGANDA-CAMPAÑAS DE PUBLICIDAD-CONCEPCION Y DISEÑO DE LA PUBLICIDAD','659','659'), 
                                    ('RELACIONES PUBLICAS','659.4','659'), 
                                    ('TECNOLOGIA QUIMICA-INDUSTRIA METALURGICA-PRODUCTOS QUIMICOS','66','66'), 
                                    ('INDUSTRIA DEL VIDRIO, CERAMICA, CEMENTO Y HORMIGON','666','66'), 
                                    ('INDUSTRIAS TINTOREAS-COLORANTES-PINTURAS','667','66'),
                                    ('METALURGICA','669','67'),
                                    ('ARTESANIAS-ARTICULOS DE METALES Y PIEDRAS PRECIOSAS-ARTICULOS DE HIERRO Y ACERO-INDUSTRIA DE LA MADERA-INDUSTRIA DEL CUERO-INDUSTRIA DEL PAPEL-INDUSTRIA TEXTIL-INDUSTRIA DEL CAUCHO Y PLASTICO','67/68','67'), 
                                    ('COMPUTACION Y SUS APLICACIONES-SOFTWARE-HARDWARE-LENGUAGES DE PROGRAMACION','681.3','67'), 
                                    ('MATERIALES PARA LA CONSTRUCCION','69','67'), 
                                    ('TEORIA GENERAL DEL ARTE-FILOSOFIA DEL ARTE','7','70'), 
                                    ('HISTORIA DEL ARTE (desarrollo cronológico)','7[091]','70'), 
                                    ('ARTE ARGENTINO','7[82]','70'), 
                                    ('RESTAURACION-CONSERVACION','7.025','70'), 
                                    ('ARTE PREHISTORICO-ARTE PRIMITIVO (antigüo y moderno)','7.031','70'), 
                                    ('ARTE PRECOLOMBINO AMERICANO (hasta la época actual)','7.031.7','70'), 
                                    ('ARTE ORIENTAL Y ASIATICO ARTE AFRICANO','7.032','70'), 
                                    ('ARTE DE GRECIA Y ROMA','7.032.7','70'), 
                                    ('ARTE MEDIEVAL.ARTE Y ESTILO ARTISTICO DE LA EDAD MEDIA','7.033','70'), 
                                    ('RENACIMIENTO','7.034 ','70'), 
                                    ('MOVIMIENTOS ARTISTICOS MODERNOSREALISMO, IMPRESIONISMO, NATURALISMO,FUNCIONALISMO, EXPRESIONISMO, ARTE ABSTRACTO,','7.036','70'), 
                                    ('PROFESIONES Y ACTIVIDADES RELACIONADAS CON LAS ARTES Y EL ENTRETENIMIENTO','7.07','70'), 
                                    ('ARQUITECTURA','72 ','70'), 
                                    ('CONSTRUCCION CIVIL EN GENERALEDIFICIOS PUBLICOS ADMINISTRATIVOS Y COMERCIALES','725','70'), 
                                    ('TRAS INSTALACIONES PUBLICAS: ARCOS DEL TRIUNFO,MONUMENTOS, ILUMINACION, CALLES, FUENTES , ETC.<EDIFICIOS PUBLICOS}EDIFICIOS COMERCIALES<EDIFICIOS RELIGIOSOS','74','70'), 
                                    ('ARTES PLASTICAS (técnicas, métodos, materiales)-ESCULTURA<CERAMICA','73','70'), 
                                    ('DIBUJO ARTES PLASTICAS APLICADAS CARICATURAS','74','70'), 
                                    ('PINTURA<TEORIA GENERAL','75','70'), 
                                    ('ARTES GRAFICAS (materiales, diseño de carteles)GRABADO (impresión y técnicas)','76','70'), 
                                    ('FOTOGRAFIA (técnicas y equipos)','77','70'), 
                                    ('CINEMATOGRAFIA','778.5','70'), 
                                    ('MUSICA ARGENTINA','78[82]','70'), 
                                    ('MUSICA (teoría, historia y géneros)<HISTORIA GENERAL DE LA MUSICA','781','70'), 
                                    ('TEATRO (técnicas teatrales, dirección, actuación)','792','70'), 
                                    ('BALLET','793','70'), 
                                    ('JUEGOS DE TABLERO Y DE MESA','794','79'), 
                                    ('HISTORIA DE LOS DEPORTES','796[091)','79'), 
                                    ('DEPORTES (en sus diferentes formas)','796','79'), 
                                    ('jUEGOS<GIMNASIA-EXPRESION CORPORAL','796.4','79'), 
                                    ('CONOCIMIENTO PRACTICO DE LAS LENGUAS','800.7','80'),
                                    ('LINGÜISTICA Y FILOLOGIA GENERALES-SISTEMAS ORTOGRAFICOS-CLASES DE PALABRAS-FONOLOGIA','801','80'),
                                    ('GRAMATICA<GRAMATICA COMPARADA-GRAMATICA HISTORICA.','801-5','80'),
                                    ('INGLES','802','80'),
                                    ('ALEMAN','803 ','80'),
                                    ('LENGUAS ROMANCES  ','804','80'),
                                    ('ORTOGRAFIA ESPAÑOLA','806.0-1','80'),
                                    ('GRAMATICA ESPAÑOLA','806.0-5','80'),
                                    ('ETIMOLOGIA Y FUENTES DEL ESPAÑOL','806.0-51','80'),
                                    ('LENGUAS CLASICA<S<LATIN ','807','80'),
                                    ('LENGUAS AUTOCTONAS DEL NORTE Y CENTROAMERICA','809.7','80'),
                                    ('QUICHE-OTRAS','78','80'),
                                    ('LENGUAS AUTOCTONAS SUDAMERICANASARAUCANO<MAPUCHE<CHIBCHA','809.8','80'),
                                    ('LITERATURA','82','82'),
                                    ('HISTORIA DE LA LITERATURA','82[091]','82'),
                                    ('POESIA<FABULA-APOLOGOSS ','82-1','82'),
                                    ('TEATRO HISTORIA DEL GENERO TEATRAL','82-2','82'),
                                    ('NARRACIONES ','82-3','82'),
                                    ('SATIRAS-HUMOR-EPIGRAMAS','82-7','82'),
                                    ('POLIGRAFIAS','82-82','82'),
                                    ('MAXIMAS, SENTENCIAS, AFORISMOS, REFRANES, ETC.','82-84','82'),
                                    ('LITERATURA INFANTIL','82-93','82'),
                                    ('POESIA INFANTIL','82-93-1','82'),
                                    ('TEATRO INFANTIL','82-93-2','82'),
                                    ('CUENTOS Y NOVELAS DE AMOR','82-93[2] ','82'),
                                    ('CUENTOS Y NOVELAS DE ANIMALES','82-93[3]','82'),
                                    ('CUENTOS DE AVENTURAS','82-93[4]','82'),
                                    ('CUENTOS DE HUMOR','82-93[5]','82'),
                                    ('CUENTOS MARAVILLOSOS','82-93[6]','82'),
                                    ('CUENTOS DE INVENTOS','82-93[7]','82'),
                                    ('CUENTOS DE TERROR','82-93[8]','82'),
                                    ('OBRAS DE CIENCIA Y FILOSOFIA COMO LITERATURA','82-96','82'),
                                    ('ACTIVIDAD Y TECNICA LITERARIA-ORATORIA Y RETORICA','82.08','82'),
                                    ('CRITICA LITERARIA-ESTUDIOS LITERARIOS','82.09','82'),
                                    ('HISTORIA DE LA LITERATURA -INGLESA LITERATURA INGLESA','820','82'),
                                    ('LITERATURA NORTEAMERICANA Y CANADIENSE','820[73]','82'),
                                    ('LITERATURA ALEMANA','830','82'),
                                    ('LITERATURA DE LOS PAISES BAJOS','839.3','82'),
                                    ('LITERATURA NORUEGALITERATURA SUECA-LITERATURA DANESA-LITERATURA FINESA','839.6 ','82'),
                                    ('LITERATURA FRANCESA -HISTORIA DE LA LITERATURA FRANCESA-CRITICA Y ESTUDIOS LITERARIOS FRANCESES','840','82'),
                                    ('TEATRO FRANCES','840-2','82'),
                                    ('TEATRO ESPAÑOL','860-2','82'),
                                    ('POESIA FRANCESA','840-1','82'),
                                    ('NARRATIVA FRANCESA','840-3','82'),
                                    ('LITERATURA ITALIANA<TEATRO ITALIANO<NARRATIVA ITALIANA<POESIA ITALIANA','850','82'),
                                    ('LITERATURA ESPAÑOLA -LITERATURA VASCA','860','82'),
                                    ('HISTORIA DE LA LITERATURA ESPAÑOLA','860[091]','82'),
                                    ('POESIA ESPAÑOLA','860-1','82'),
                                    ('NARRATIVA ESPAÑOLA','860-3','82'),
                                    ('ENSAYOS ESPAÑOLES','860-4','82'),
                                    ('ANTOLOGIAS DE LITERATURA ESPAÑOLA','860-82','82'),
                                    ('ESTETICA LITERARIA ESPAÑOLA-CRITICA LITERARIA ESPAÑOLA','860.0','82'),
                                    ('LITERATURA LATINOAMERICANA ','860 [7/8]','82'),
                                    ('LITERATURA MEXICANA-POESIA MEXICANA-TEATRO MEXICANO-NARRATIVA MEXICANA','860[72]','82'),
                                    ('LITERATURA CENTROAMERICANA Y DEL CARIBE','860[728]','82'),
                                    ('LITERATURA ARGENTINA ','860[82]','82'),
                                    ('CRITICA LITERARIA ARGENTINA','860[82].09','82'),
                                    ('HISTORIA DE LA LITERATURA ARGENTINA','860[82][091]','82'),
                                    ('POESIA ARGENTINA','860[82]-1','82'),
                                    ('TEATRO ARGENTINO','860[82]-2','82'),
                                    ('NARRATIVA ARGENTINA','860[82]-3','82'),
                                    ('ENSAYOS ARGENTINOS','860[82]-4','82'),
                                    ('POLIGRAFIAS ARGENTINAS','860[82]-82','82'),
                                    ('HISTORIA ARGENTINA COMO GENERO LITERARIO-CRONICAS ARGENTINAS','860[82]-94','82'),
                                    ('LITERATURA CHILENA','860[83]','82'),
                                    ('LITERATURA PERUANA','860[85]','82'),
                                    ('LITERATURA COLOMBIANA','860[861]','82'),
                                    ('LITERATURA URUGUAYA','860[899]','82'),
                                    ('LITERATURA PORTUGUESA','869','82'),
                                    ('LITERATURA BRA','869[81]','82'),
                                    ('LITERATURA GRECO-LATINA-HISTORIA DE LA LITERATURA GRIEGA Y LATINA','871/875','82'),
                                    ('LITERATURA RUSA','882','82'),
                                    ('LITERATURA CHECA','885.0','82'),
                                    ('LITERATURA SERBIA-LITERATURA YUGOESLAVA-LITERATURA CROATA-LITERATURA BULGARA-LITERATURA RUMANA','886.1','82'),
                                    ('LITERATURA HEBREA','892.4','82'),
                                    ('LITERATURA ARABE','892.7','82'),
                                    ('LITERATURA TURCA-LITERATURA HUNGARA','894','82'),
                                    ('LITERATURA ASIATICA','895','82'),
                                    ('LITERATURA AMERINDIA (azteca, maya, guaraní, araucana, quechua)','897','82'),
                                    ('ARQUEOLOGIA','902','90'),
                                    ('PREHISTORIA ','903','90'),
                                    ('GEOGRAFIA (como ciencia)-CARTOGRAFIA-EXPLORACIONES','910','90'),
                                    ('PARQUES NACIONALES','910.5','90'),
                                    ('GEOGRAFIA FISICA','911.2','90'),
                                    ('GEOGRAFIA POLITICA-GEOGRAFIA HUMANA-GEOGRAFIA ECONOMICA','911.3 ','90'),
                                    ('GEOGRAFIA DE EUROPA','914','90'),
                                    ('GEOGRAFIA DE ASIA','915','90'),
                                    ('GEOGRAFIA DE AFRICA','916','90'),
                                    ('GEOGRAFIA DE AMERICA DEL NORTE','917','90'),
                                    ('GEOGRAFIA DE AMERICA CENTRAL','917.5 ','90'),
                                    ('GEOGRAFIA DE AMERICA DEL SUR','918','90'),
                                    ('GEOGRAFIA DE LA ARGENTINA-GEOGRAFIA FISICA, HUMANA Y ECONOMICA','918.2','90'),
                                    ('GEOGRAFIA DE LAS REGIONES DEL PACIFICO SUR, DE AUSTRALASIA Y DE LAS REGIONES POLARES','919','90'),
                                    ('BIOGRAFIAS (ingresarán por el biografiado, agregando, en un segundo nivel de identificación alfabética, al autor)','929','92'),
                                    ('BIOGRAFIAS ARGENTINAS ','929[82]','92'),#hasta aca
                                    ('GENEALOGIA-HERALDICA ','929.5','92'),
                                    ('NOBLEZA-ORDENES DE CABALLERIA-BANDERAS, PENDONES, ESTANDARTES','929.7','92'),
                                    ('HISTORIOGRAFIA-TEORIA DE LA HISTORIA','930','93'),
                                    ('DIPLOMATICA -PALEOGRAFIA-EPIGRAFIA','930.2','93'),
                                    ('HISTORIA UNIVERSAL EN SENTIDO PROPIO-HISTORIA DE LA CIVILIZACION-HISTORIA DE LA CULTURA','930.8','93'),
                                    ('HISTORIA ANTIGUA-HISTORIA DE LOS PUEBLOS DE LA ANTIGUEDAD-ANTIGUA CHINA-ANTIGUO EGIPTO','931','93'),
                                    ('HISTORIA DE LOS PUEBLOS DEL NORTE, ESTE Y OESTE DE-EUROPA HASTA EL 476 D.C. ','936','93'),
                                    ('HISTORIA DE GRECIA Y ROMA','937/938','93'),
                                    ('HISTORIA DE AMERICA PRECOLOMBINA (aborígenes)','939','93'),
                                    ('HISTORIA DE EUROPA','940','93'),
                                    ('HISTORIA DE LA EDAD MEDIA (en sentido amplio, del 375 d.C. a1492)','940.1','93'),
                                    ('HISTORIA MODERNA Y CONTEMPORANEA','940.2','93'),
                                    ('PRIMERA GUERRA MUNDIAL','940.3','93'),
                                    ('SEGUNDA GUERRA MUNDIAL','940.53','93'),
                                    ('HISTORIA DE ASIA-HISTORIA DE AFRICA','950/960','93'),
                                    ('HISTORIA DE AMERICA ','970/980','93'),
                                    ('HISTORIA DE MEXICO, AMERICA CENTRAL Y EL CARIBE','972','93'),
                                    ('HISTORIA DE LOS ESTADOS UNIDOS','973','93'),
                                    ('HISTORIA DE AMERICA DEL SUR','980','93'),
                                    ('HISTORIA DE LA ARGENTINA','982','93'),
                                    ('EPOCA DE DESCUBRIMIENTO Y CONQUISTA DEL RIO DE LA PLATA','982.02','93'),
                                    ('HISTORIA DE LA EPOCA VIRREINAL','982.03','93'),
                                    ('HISTORIA DE LA REVOLUCION DE MAYO','982.04','93'),
                                    ('HISTORIA DEL CONGRESO DE TUCUMAN','982.043','93'),
                                    ('GUERRAS CIVILES ARGENTINAS. ANARQUIA DE 1820.-ROSAS. ORGANIZACIÓN NACIONAL-FORMACION NACION – ESTADO (1852-1890)','982.05','93'),
                                    ('HISTORIA DE LA GENERACION DEL 80','982.06','93'),
                                    ('PRESIDENCIAS. DEMOCRACIA. UCR. OLIGARQUIA.<PERONISMO. TRANSICION. REVOLUCION. GOBIERNOS<MILITARES. NUEVA DEMOCRACIA','982.07 ','93'),
                                    ('HISTORIA DE LA CIUDAD DE BUENOS AIRES','982.10','93'),
                                    ('HISTORIA DE BUENOS AIRES (PROVINCIA)','982.12','93'),
                                    ('HISTORIA DE LA PAMPA','982.13','93'),
                                    ('HISTORIA DE CORDOBA','982.15','93'),
                                    ('HISTORIA DE SANTA FE','982.16','93'),
                                    ('HISTORIA DE SANTIAGO DEL ESTERO','982.17','93'),
                                    ('HISTORIA DEL CHACO','982.18 ','93'),
                                    ('HISTORIA DE FORMOSA','982.19','93'),
                                    ('HISTORIA DE ENTRE RIOS','982.21','93'),
                                    ('HISTORIA DE CORRIENTES','982.22','93'),
                                    ('HISTORIA DE MISIONES','982.23','93'),
                                    ('HISTORIA DE MENDOZA','982.25','93'),
                                    ('HISTORIA DE SAN JUAN','982.52','93'),
                                    ('HISTORIA DE SAN LUIS','982.57','93'),
                                    ('HISTORIA DE LA RIOJA','982.61','93'),
                                    ('HISTORIA DE CATAMARCA','982.63','93'),
                                    ('HISTORIA DE TUCUMAN','982.65','93'),
                                    ('HISTORIA DE SALTA','982.66','93'),
                                    ('HISTORIA DE JUJUY','982.69','93'),
                                    ('HISTORIA DE LA PATAGONIA','982.81/88 ','93'),
                                    ('HISTORIA DE NEUQUEN','982.81','93'),
                                    ('HISTORIA DE RIO NEGRO','982.82','93'),
                                    ('HISTORIA DE CHUBUT','982.86','93'),
                                    ('HISTORIA DE TIERRA DEL FUEGO','982.90','93'),
                                    ('HISTORIA DE LAS ISLAS MALVINAS','982.91','93'),
                                    ('HISTORIA DEL BEAGLE Y DEL ATLANTICO SUR','982.92','93'),
                                    ('HISTORIA DE LA ANTARTIDA ARGENTINA','982.94','93'),
                                    ('HISTORIA DE AUSTRALIA, OCEANIA Y DE LAS REGIONES ARTICAS Y ANTA','990','93')
                                ");

            $this->db->query("INSERT INTO `languaje`(`languaje_desc`)
                                VALUES ('Español'),
                                ('Ingles'),
                                ('Portugues'),
                                ('Chino mandarin'),
                                ('Frances')
                            ");

            $this->db->query("INSERT INTO `book_status`(`book_status_id`, `book_status_desc`)
                                VALUES ('1','Disponible'),
                                ('2' ,'Copia única'),
                                ('3 ','Reservado'),
                                ('4', 'Prestado'),
                                ('5' ,'No disponoble')
                            ");

            $this->db->query("INSERT INTO `user_type`(`user_type_id`, `user_type_desc`)
                                VALUES ('1','admin'),
                                    ('2','alumno'),
                                    ('3','docente'),
                                    ('4','no-docente'),
                                    ('5','graduado')
                            ");

            $this->db->query("INSERT INTO `school`(`school_name`) 
                                VALUES ('Escuela de Ciencias de la Salud'),
                                    ('Escuela de Ingeniería y Ciencias Ambientales'),
                                    ('Escuela de Gestión de Empresas y Economía'),
                                    ('Escuela de Ciencias Sociales y Educación')
                            ");

            $this->db->query("INSERT INTO `career`(`career_name`, `school_id`) 
                                VALUES ('LICENCIATURA EN KINESIOLOGÍA Y FISIATRÍA','1'),
                                    ('LICENCIATURA EN OBSTETRICIA','1'),
                                    ('LICENCIATURA EN ENFERMERÍA','1'),
                                    ('LICENCIATURA EN ACTIVIDAD FÍSICA','1'),
                                    ('MEDICINA','1'),
                                    ('BIOINGENIERIA','2'),
                                    ('INGENIERÍA EN SISTEMAS DE INFORMACIÓN','2'),
                                    ('INGENIERÍA EN AGROINDUSTRIA','2'),
                                    ('ANALISTA EN SISTEMAS DE INFORMACIÓN','2'),
                                    ('PROGRAMADOR UNIVERSITARIO DE SISTEMAS','2'),
                                    ('TECNICATURA SUPERIOR EN GESTIÓN AMBIENTAL','2'),
                                    ('TECNICATURA UNIVERSITARIA EN AGROALIMENTOS','2'),
                                    ('LICENCIATURA EN ECONOMÍA','3'),
                                    ('LICENCIATURA EN DISEÑO DE COMUNICACIÓN','3'),
                                    ('LICENCIATURA EN LOGÍSTICA','3'),
                                    ('TECNICATURA UNIVERSITARIA EN GESTIÓN DEPORTIVA','3'),
                                    ('TECNICATURA UNIVERSITARIA EN MARKETING CULTURAL Y DEPORTIVO','3'),
                                    ('PROFESORADO DE EDUCACIÓN INICIAL','4'),
                                    ('PROFESORADO DE  EDUCACIÓN PRIMARIA','4')"
                            );

            #consulta para poner en cascada a book
            #ALTER TABLE `book` DROP FOREIGN KEY `fk_book_book_status1`; ALTER TABLE `book` ADD CONSTRAINT `fk_book_book_status1` FOREIGN KEY (`book_status_id`) REFERENCES `book_status`(`book_status_id`) ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE `book` DROP FOREIGN KEY `fk_book_category1`; ALTER TABLE `book` ADD CONSTRAINT `fk_book_category1` FOREIGN KEY (`category_id`) REFERENCES `category`(`category_id`) ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE `book` DROP FOREIGN KEY `fk_book_languaje1`; ALTER TABLE `book` ADD CONSTRAINT `fk_book_languaje1` FOREIGN KEY (`languaje_id`) REFERENCES `languaje`(`languaje_id`) ON DELETE CASCADE ON UPDATE CAS
        }
    }
?>